spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: value-engine-group-v3
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 3

  data:
    redis:
      host: localhost
      port: 6379

  application:
    name: backend-engine
  datasource:
    url: jdbc:postgresql://localhost:5435/valueengine
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true